resources:
- ../../base
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
nameSuffix: -dev
images:
- name: ghcr.io/LuckyMenneke/gitops-assignment
  newName: ghcr.io/luckymenneke/gitops-assignment
  newTag: sha-9803976bfb3cc5d31adc9555b8e22d2b057e0eeb
