resources:
- ../../base
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
nameSuffix: -qa
images:
- name: ghcr.io/LuckyMenneke/gitops-assignment
  newName: ghcr.io/luckymenneke/gitops-assignment
  newTag: sha-20e45e17cd9802f7f30c4cf7f2a5617a56e3e76b
